services:
  mongo:
    image: mongo:latest
    ports:
     - 27017:27017
     
  backend:
    build: ./backend
    ports:
    - 5000:5000
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
     - 3000:3000
    depends_on:
      - backend
